services:
  complement-fox:
    build: .
    env_file:
      - .env
    volumes:
      - data:/usr/etc/app/data
      - ./messages:/usr/etc/app/messages
    networks:
      - proxy
    restart: always

volumes:
  data:

networks:
  proxy:
    name: proxy
    external: true
